name: testflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run test
      shell: bash
      env:
        secret: ${{ secrets.TestSecret }}
      run: >
        if [[ "${secret}" ]]; then echo "YES"; exit 0; else echo "NO"; exit 1; fi

